### ISSUE TITLE
User management issues

### ISSUE THREAD

**Issue by manuelsprung** [HADatAc/sir#28]
I experience some user management issues

I first created a new contributor account with my admin account, and then registered a series of questionnaires in the contributor account. When I later switched back to the admin account, I noticed that am not able to manage content registered in the contributor account. Not sure if this is intentend, but how can I as the admin approve or decline new contributions?

**Comment by paulopinheiro1234** [comment]
Please note that in its current version, SIR has no mechanism for one to "approve" or "decline". Everything that is entered is immediately available for anyone to see. 

Also, any content can only be modified by the manager of the content - no one else. The authorial and editorial capabilities of SIR are expected to be included in the version 0.6 since they still need to be implemented. Issues #12, #13 and #14 are the ones addressing the issue reported above, and they have already been scheduled to be implemented.

I will close this issue since it is already addressed in previous issues.
